StudentDBWeb/Controllers/TeacherController.cs
using Newtonsoft.Json;
using StudentBLL;
using StudentModel;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentDBWeb.Controllers
{
    public class TeacherController : Controller
    {
        int _currentPage = 1;
        int _pageSize = 7;
        private IList<TSTU_B_Student> _allProducts = new List<TSTU_B_Student>();
        ObservableCollection<TSTU_B_Student> stu = new ObservableCollection<TSTU_B_Student>();
        
        // GET: Teacher
        public ActionResult Index()
        {
            if (Session["Name"] != null)
            {
                ViewBag.Name = Session["Name"];
            }
            if (Session["FsCla_Name"] != null)
            {
                ViewBag.FsCla_Name = Session["FsCla_Name"];
            }
            if (Session["count"] != null)
            {
                ViewBag.count = Session["count"];
            }
            if (Session["Subject_count"] != null)
            {
                ViewBag.Subject_count = Session["Subject_count"];
            }
            if (Session["id"] != null)
            {
                ViewBag.id = Session["id"];
            }
            if (Session["Name"] == null || Session["FsCla_Name"] == null || Session["count"] == null || Session["Subject_count"] == null)
            {
                return Redirect("/Teacher/Null404");
            }
            return View();
        }
        /// <summary>
        /// 总分
        /// </summary>
        /// <returns></returns>
        public ActionResult Total(string name, int? size,int? page = 1)
        {
            ViewBag.stuname = name;
            if (Session["Name"] != null)
            {
                ViewBag.Name = Session["Name"];
            }
            if (Session["FsCla_Name"] != null)
            {
                ViewBag.FsCla_Name = Session["FsCla_Name"];
            }
            if (Session["count"] != null)
            {
                ViewBag.count = Session["count"];
            }
            if (Session["Subject_count"] != null)
            {
                ViewBag.Subject_count = Session["Subject_count"];
            }
            if (Session["id"] != null)
            {
                ViewBag.id = Session["id"];
            }
            if (Session["Name"] == null || Session["FsCla_Name"] == null || Session["count"] == null || Session["Subject_count"] == null)
            {
                return Redirect("/Teacher/Null404");
            }
            SvcResult<TSTU_B_Score> Result = LoginBll.Result(name);

            if (Result == null)
            {
                return Redirect("/Teacher/Null404");
            }
            //分页
            _currentPage = page.HasValue ? page.Value : _currentPage;
            _pageSize = size.HasValue ? size.Value : _pageSize;
            ViewBag.size = _pageSize;
            var model = Result.ObjList.ToPagedList(_currentPage, _pageSize);
            ViewBag.PageCount = Math.Ceiling((double)model.TotalItemCount / (double)model.PageSize);
            return View(model);
        }
        [HttpPost]
        public ActionResult Total(int id)
        {
            if (id == 0)
            {
                id = 92;
            }
            SvcResult<TSTU_B_Student> Personal = TeacherBll.Sum_detil(id);
            Session["Personal"] = Personal.ObjList;
            if (Session["Personal"] != null)
            {
                ViewBag.Personal = Session["Personal"];
                Personal.Error = "zzzzzzzz";
            }
            else
            {
                SvcResult<TSTU_B_Student> S = TeacherBll.Sum_detil(74);
                ViewBag.Personal = S.ObjList;
                Personal.Error = "错误";
            }
            return Json(Personal.ObjList);
        }
        /// <summary>
        /// 各科排名
        /// </summary>
        /// <returns></returns>
        public ActionResult Subject(int? id, int? size,int? page = 1)
        {
            ViewBag.subid = id;
            if (Session["Name"] != null)
            {
                ViewBag.Name = Session["Name"];
            }
            if (Session["FsCla_Name"] != null)
            {
                ViewBag.FsCla_Name = Session["FsCla_Name"];
            }
            if (Session["count"] != null)
            {
                ViewBag.count = Session["count"];
            }
            if (Session["Subject_count"] != null)
            {
                ViewBag.Subject_count = Session["Subject_count"];
            }
            if (Session["id"] != null)
            {
                ViewBag.id = Session["id"];
            }
            if (Session["Name"] == null || Session["FsCla_Name"] == null || Session["count"] == null || Session["Subject_count"] == null)
            {
                return Redirect("/Teacher/Null404");
            }
            SvcResult<TSTU_B_Subject> Sub = TeacherBll.Sel_Subject();
            ViewBag.sub = Sub.ObjList;
            SvcResult<TSTU_B_Student> Subject_Result = LoginBll.Subject_Result(id);
            //分页
            _currentPage = page.HasValue ? page.Value : _currentPage;
            _pageSize = size.HasValue ? size.Value : _pageSize;
            ViewBag.size = _pageSize;
            var model = Subject_Result.ObjList.ToPagedList(_currentPage, _pageSize);
            ViewBag.PageCount = Math.Ceiling((double)model.TotalItemCount / (double)model.PageSize);
            return View(model);
        }
        [HttpPost]
        public ActionResult Subject(int id)
        {
            SvcResult<TSTU_B_Subject> Sub = TeacherBll.Sel_Subject();
            ViewBag.sub = Sub.ObjList;
            SvcResult<TSTU_B_Student> Subject_Result = LoginBll.Subject_Result(id);
            if (Subject_Result == null)
            {
                return Redirect("/Default/Null404");
            }
            ViewBag.Subject = Subject_Result.ObjList;
            return Json(Subject_Result.ObjList);
        }
        /// <summary>
        /// 学生窗口
        /// </summary>
        /// <returns></returns>
        public ActionResult Student(string name,  int? size,int? page = 1)
        {

            ViewBag.stuname = name;
            if (Session["Name"] != null)
            {
                ViewBag.Name = Session["Name"];
            }
            if (Session["FsCla_Name"] != null)
            {
                ViewBag.FsCla_Name = Session["FsCla_Name"];
            }
            if (Session["count"] != null)
            {
                ViewBag.count = Session["count"];
            }
            if (Session["Subject_count"] != null)
            {
                ViewBag.Subject_count = Session["Subject_count"];
            }
            if (Session["id"] != null)
            {
                ViewBag.id = Session["id"];
            }
            if (Session["Name"] == null || Session["FsCla_Name"] == null || Session["count"] == null || Session["Subject_count"] == null)
            {
                return Redirect("/Teacher/Null404");
            }
            if (Session["FnCla_ID"] == null)
            {
                return Redirect("/Default/Null404");
            }
            if (Session["FnSub_ID"] == null)
            {
                return Redirect("/Default/Null404");
            }
            SvcResult<TSTU_B_Student> student = TeacherBll.Student(int.Parse(Session["FnCla_ID"].ToString()), name);
            if (student == null)
            {
                return Redirect("/Default/Null404");
            }
            SvcResult<TSTU_B_Class> CLASS = TeacherBll.Sel_Class();
            ViewBag.CLASS = CLASS.ObjList;
            //分页
            _currentPage = page.HasValue ? page.Value : _currentPage;
            _pageSize = size.HasValue ? size.Value : _pageSize;
            ViewBag.size = _pageSize;
            _allProducts = student.ObjList;
            var model = _allProducts.ToPagedList(_currentPage, _pageSize);
            ViewBag.PageCount = Math.Ceiling((double)model.TotalItemCount / (double)model.PageSize);
            //foreach (var i in student.ObjList)
            //{
            //    TSTU_B_Student s = new TSTU_B_Student();
            //    s.FnStu_ID = i.FnStu_ID;
            //    s.rownumber = i.rownumber;
            //    s.FsCla_Name = i.FsCla_Name;
            //    s.FsStu_Name = i.FsStu_Name;
            //    s.FsStu_Account = i.FsStu_Account;
            //    stu.Add(s);
            //}
            return View(model);
        }
        /// <summary>
        /// 学生模糊查询
        /// </summary>
        /// <param name="name"></param>
        /// <returns></returns>
        
        [HttpPost]
        public ActionResult Student(int id)
        {
            SvcResult<TSTU_B_Student> student = TeacherBll.Student(int.Parse(Session["FnCla_ID"].ToString()), "");
            return Json(student.ObjList);
        }
        /// <summary>
        /// 添加学生
        /// </summary>
        /// <returns></returns>
        public ActionResult StudentAdd()
        {
            if (Session["Name"] != null)
            {
                ViewBag.Name = Session["Name"];
            }
            if (Session["FsCla_Name"] != null)
            {
                ViewBag.FsCla_Name = Session["FsCla_Name"];
            }
            if (Session["count"] != null)
            {
                ViewBag.count = Session["count"];
            }
            if (Session["Subject_count"] != null)
            {
                ViewBag.Subject_count = Session["Subject_count"];
            }
            if (Session["id"] != null)
            {
                ViewBag.id = Session["id"];
            }
            if (Session["FnCla_ID"] == null)
            {
                return Redirect("/Default/Null404");
            }
            if (Session["Name"] == null || Session["FsCla_Name"] == null || Session["count"] == null || Session["Subject_count"] == null)
            {

StudentDBWeb/Views/Teacher/Edit.cshtml
@model IEnumerable<StudentModel.TSTU_B_Student>
    @using StudentModel;
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_TeaPage.cshtml";
}

@foreach (var i in Model)
{
    <form id="studentEdit">

        <div class="form-group">
            <label for="exampleInputEmail1">账号</label>
            <input type="text" class="form-control" name="FsStu_Account" aria-describedby="emailHelp" placeholder="请输入账号" value="@i.FsStu_Account">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">姓名</label>
            <input type="text" class="form-control" name="FsStu_Name" aria-describedby="emailHelp" placeholder="请输入姓名" value="@i.FsStu_Name">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">密码</label>
            <input type="password" class="form-control" name="FsStu_Psw" id="exampleInputPassword1" placeholder="请输入密码" value="@i.FsStu_Psw">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">班级</label>
            <select class="custom-select">
                @foreach (var item in ViewBag.stu as List<TSTU_B_Class>)
                {
                    if (i.FnCla_ID == item.FnCla_ID)
                    {
                        <option name="FnCla_ID" value="@item.FnCla_ID" selected="selected">@item.FsCla_Name</option>
                    }
                    else
                    {
                        <option name="FnCla_ID" value="@item.FnCla_ID">@item.FsCla_Name</option>
                    }

                }
            </select>
        </div>

        <button type="button" class="btn btn-primary">保存</button>
    </form>
}

StudentDBWeb/Views/Teacher/Null404.cshtml
@{
    ViewBag.Title = "Null404";
    Layout = "~/Views/Shared/_TeaPage.cshtml";
}


<div id="content">

    <!-- Topbar -->
    

    <!-- End of Topbar -->
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- 404 Error Text -->
        <div class="text-center">
            <div class="error mx-auto" data-text="404">404</div>
            <p class="lead text-gray-800 mb-5">Page Not Found</p>
            <p class="text-gray-500 mb-0">It looks like you found a glitch in the matrix...</p>
            <a href="~/Default/Login">← Back to Login</a>
        </div>

    </div>
    <!-- /.container-fluid -->

</div>

StudentDBWeb/Views/Teacher/PartialPage.cshtml
@using StudentModel;
@model IPagedList<StudentModel.TSTU_B_Student>
@if (Model != null)
{

    foreach (var item in Model.Source)
    {
        <tr>
            <td>@item.rownumber</td>
            <td>@item.FsStu_Name </td>
            <td>@item.FsStu_Account </td>
            <td>@item.FsCla_Name  </td>
            <td>
                <a class="edit" href="~/Teacher/Edit?id=@item.FnStu_ID">编辑</a>
                <a class="delete" data-id="@item.FnStu_ID">删除</a>
            </td>
        </tr>
    }
}

StudentDBWeb/Views/Teacher/ScoreAdd.cshtml
@model IPagedList<StudentModel.TSTU_B_Student>
@using StudentModel;
@{
    ViewBag.Title = "ScoreAdd";
    Layout = "~/Views/Shared/_TeaPage.cshtml";
}

<div class="card shadow mb-4 ScoreAddPage">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">录入成绩</h6>
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12" id="ScoreAddDiv">
                        <table class="table table-bordered dataTable" role="grid" aria-describedby="dataTable_info" style="width: 100%;" width="100%" cellspacing="0">
                            <thead>
                                <tr role="row">
                                    <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending">序号</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">姓名</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">学号</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">班级</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">科目</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">成绩</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">操作</th>
                                </tr>
                            </thead>

                            <tbody>
                                @*<asp:Repeater runat="server" DataSource='<%#ViewData["Students"]%>'>
            <template>
                <tr role="row">
                    <td><%#Eval("FsStu_Account")%></td>
                    <td><%#Eval("FsStu_Account")%></td>
                    <td><%#Eval("FsStu_Account")%></td>
                    <td><%#Eval("FsStu_Account")%></td>
                    <td><%#Eval("FsStu_Account")%></td>
                    <td><%#Eval("FsStu_Account")%></td>
                    <td><%#Eval("FsStu_Account")%></td>
                </tr>
            </template>
        </asp:Repeater>*@
                                @foreach (var item in Model.Source)
                                {
                                    <tr>
                                        <td>@item.rownumber</td>
                                        <td>@item.FsStu_Name </td>
                                        <td>@item.FsStu_Account </td>
                                        <td>@item.FsCla_Name  </td>
                                        <td>@item.FsSub_Name </td>
                                        <td>@item.FnSco_Result </td>
                                        <td>
                                            <button class="btn btn-success btn-icon-split btn_model" id="btn_model" data-toggle="modal" data-target="#exampleModal" data-whatever="@item.FnStu_ID">
                                                <span class="text">录入</span>
                                            </button>
                                        </td>
                                    </tr>
                                }
                                @if (ViewBag.score!=null)
                                {
                                    foreach (var item in ViewBag.score as List<TSTU_B_Student>)
                                    {
                                        <tr>
                                            <td>@item.rownumber</td>
                                            <td>@item.FsStu_Name </td>
                                            <td>@item.FsStu_Account </td>
                                            <td>@item.FsCla_Name  </td>
                                            <td>@item.FsSub_Name </td>
                                            <td>@item.FnSco_Result </td>
                                            <td>
                                                <button class="btn btn-success btn-icon-split btn_model" id="btn_model" data-toggle="modal" data-target="#exampleModal" data-whatever="@item.FnStu_ID">
                                                    <span class="text">录入</span>
                                                </button>
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row">
                    @if (Model != null)
                    {
                        <div class="col-sm-12 col-md-3">
                            <div id="dataTable_info" role="status" aria-live="polite">
                                当前第 @Model.CurrentPage/@ViewBag.PageCount 页 每页显示 @Model.PageSize 条数据 共 @Model.TotalItemCount 条数据
                            </div>
                        </div>

                        <div class="col-md-3 col-sm-12">
                            @using (Html.BeginForm("ScoreAdd", "Teacher", FormMethod.Get, new { id = "PagingForm" }))
                            {
                                <div class="dataTables_length" id="dataTable_length">
                                    <label>
                                        Show
                                        <select name="size" aria-controls="dataTable" class="custom-select custom-select-sm form-control form-control-sm">
                                            <option value="@ViewBag.size">@ViewBag.size</option>
                                            <option value="5">5</option>
                                            <option value="10">10</option>
                                            <option value="20">20</option>
                                            <option value="30">30</option>
                                            <option value="50">50</option>
                                            <option value="70">70</option>
                                            <option value="100">100</option>
                                        </select>
                                        entries
                                    </label>
                                </div>
                            }
                        </div>

                        <div class="col-sm-12 col-md-6">
                            <div class="dataTables_paginate paging_simple_numbers" id="dataTable_paginate">
                                @Html.Pager(Model.PageSize, Model.CurrentPage, Model.TotalItemCount).Options(o => o.HtmlAttributes(new { @class = "pagination" }).RouteValues(new { size = @ViewBag.size }))
                            </div>

                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable ">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">分数详情</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input type="hidden" class="form-control" id="recipient-name" name="id">
                <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group row">
                                <label for="inputEmail3" class="col-sm-2 col-form-label">成绩</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" hidden="hidden" id="recipient-name" />
                                    <input type="text" class="form-control" id="score_input" placeholder="请输入成绩">
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal" id="ScoreClose">Close</button>
                <button type="button" class="btn btn-primary" id="SaveScore">Save changes</button>
            </div>
        </div>
    </div>
</div>

StudentDBWeb/Views/Teacher/Student.cshtml
@model IPagedList<StudentModel.TSTU_B_Student>
@using StudentModel;
@{
    ViewBag.Title = "Student";
    Layout = "~/Views/Shared/_TeaPage.cshtml";
}


<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">学生窗口</h6>
    </div>
    <div class="row">
        <div class="input-group col-md-4 col-sm-6 col-lg-2 col-xl-2">
            <div class="input-group-append">
                <a class="btn btn-primary" runat="server" href="~/Teacher/StudentAdd">
                    <i class="fas fa-plus fa-sm">添加学生</i>
                </a>
            </div>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-3 col-xl-2 offset-md-4 offset-lg-7 offset-xl-8">
            @using (Html.BeginForm("Student", "Teacher", FormMethod.Get))
            {
                <div class="input-group">
                    <input type="text" name="name" class="form-control bg-light border-0 small StuinputSearch" placeholder="请输入姓名查询..." value="@ViewBag.stuname" aria-label="Search" id="id" aria-describedby="basic-addon2">
                    <input type="hidden" name="size" value="@ViewBag.size" />
                    <div class="input-group-append ">
                        <button type="submit" class="btn btn-primary StubtnSearch">
                            <i id="ajax-loader" class="fas fa-search fa-sm"></i>
                        </button>
                    </div>
                </div>
            }
        </div>
    </div>


    <div class="card-body">
        <div class="table-responsive">
            <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12">
                        <table class="table table-bordered dataTable" id="" role="grid" aria-describedby="dataTable_info" style="width: 100%;" width="100%" cellspacing="0">
                            <thead>
                                <tr role="row">
                                    <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending">序号</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">姓名</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">学号</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">班级</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">操作</th>
                                </tr>
                            </thead>

                            <tbody class="T_student" id="T_student">
                                @if (Model != null)
                                {

                                    foreach (var item in Model.Source)
                                    {
                                        <tr>
                                            <td>@item.rownumber</td>
                                            <td>@item.FsStu_Name </td>
                                            <td>@item.FsStu_Account </td>
                                            <td>@item.FsCla_Name  </td>
                                            <td>
                                                <a class="edit" href="~/Teacher/Edit?id=@item.FnStu_ID">编辑</a>
                                                <a class="delete" data-id="@item.FnStu_ID">删除</a>
                                            </td>
                                        </tr>
                                    }
                                }
                                @*<asp:Repeater runat="server" DataSource='<%#ViewData["Students"]%>'>
                                        <template>
                                            <tr role="row">
                                                <td><%#Eval("FsStu_Account")%></td>
                                                <td><%#Eval("FsStu_Account")%></td>
                                                <td><%#Eval("FsStu_Account")%></td>
                                                <td><%#Eval("FsStu_Account")%></td>
                                                <td><%#Eval("FsStu_Account")%></td>
                                                <td><%#Eval("FsStu_Account")%></td>
                                                <td><%#Eval("FsStu_Account")%></td>
                                            </tr>
                                        </template>
                                    </asp:Repeater>*@
                                @*
                                                @foreach (var item in Model)
                                                {
                                                    <tr>
                                                        <td>@Html.DisplayFor(modelItem => item.rownumber) </td>
                                                        <td>@Html.DisplayFor(modelItem => item.FsStu_Name) </td>
                                                        <td>@Html.DisplayFor(modelItem => item.FsStu_Account) </td>
                                                        <td>@Html.DisplayFor(modelItem => item.FsCla_Name)  </td>
                                                        <td>
                                                            <a class="edit" href="~/Teacher/Edit?id=@item.FnStu_ID">编辑</a>
                                                            <a class="delete" data-id="@item.FnStu_ID">删除</a>-->
                                                            <button class="btn btn-success btn-icon-split btn_model" id="btn_model" data-toggle="modal" data-target="#exampleModal" data-whatever="@Html.DisplayFor(modelItem => item.FnStu_ID)">
                                        <span class="text">修改</span>
                                    </button>
                                    <button class="btn btn-danger btn-icon-split btn_model" id="btn_model" data-toggle="modal" data-target="#exampleModal" data-whatever="@Html.DisplayFor(modelItem => item.FnStu_ID)">
                                        <span class="text">删除</span>
                                    </button>
                                                        </td>
                                                    </tr>
                                                }*@
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row fenye">
                    <div class="col-sm-12 col-md-3">
                        <div   id="dataTable_info" role="status" aria-live="polite">
                            当前第 @Model.CurrentPage/@ViewBag.PageCount 页 每页显示 @Model.PageSize 条数据 共 @Model.TotalItemCount 条数据
                        </div>
                    </div>

                    <div class="col-md-3 col-sm-12">
                        @using (Html.BeginForm("Student", "Teacher", FormMethod.Get,new { id= "PagingForm"}))
                        {
                            <div class="dataTables_length" id="dataTable_length">
                                <label>
                                    Show
                                    <input type="hidden" value="@ViewBag.stuname" name="name" />
                                    <select name="size" aria-controls="dataTable" class="custom-select custom-select-sm form-control form-control-sm">
                                        <option value="@ViewBag.size">@ViewBag.size</option>
                                        <option value="5">5</option>
                                        <option value="10">10</option>
                                        <option value="20">20</option>
                                        <option value="30">30</option>
                                        <option value="50">50</option>
                                        <option value="70">70</option>
                                        <option value="100">100</option>
                                    </select>
                                    entries
                                </label>
                            </div>
                        }
                    </div>

                    <div class="col-sm-12 col-md-6">
                        <div class="dataTables_paginate paging_simple_numbers" id="dataTable_paginate">
                            @Html.Pager(Model.PageSize, Model.CurrentPage, Model.TotalItemCount).Options(o => o.HtmlAttributes(new { @class = "pagination" }).RouteValues(new { name = ViewBag.stuname,size=ViewBag.size }))
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>