StudentDBWeb/Controllers/DefaultController.cs
using StudentModel;
using System;
using StudentBLL;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;

namespace StudentDBWeb.Controllers
{
    public class DefaultController : Controller
    {
        int _currentPage = 1;
        int _pageSize = 7;
        private IList<TSTU_B_Student> _allProducts = new List<TSTU_B_Student>();
        StudentDB db = new StudentDB();
        // GET:
        // 
        public ActionResult Index()
        {
            if (Session["Name"] != null)
            {
                ViewBag.Name = Session["Name"];
            }
            if (Session["FsCla_Name"] != null)
            {
                ViewBag.FsCla_Name = Session["FsCla_Name"];
            }
            if (Session["count"] != null)
            {
                ViewBag.count = Session["count"];
            }
            if (Session["Subject_count"] != null)
            {
                ViewBag.Subject_count = Session["Subject_count"];
            }
            if (Session["id"] != null)
            {
                ViewBag.id = Session["id"];
            }
            if (Session["Name"] == null || Session["FsCla_Name"] == null || Session["count"] == null || Session["Subject_count"] == null)
            {
                return Redirect("/Default/Null404");
            }
            return View();
        }
        /// <summary>
        /// 个人成绩
        /// </summary>
        /// <returns></returns>
        public int stuid = 0;
        public ActionResult Personal(int? id, int? size, int? page = 1)
        {
            if (Session["Name"] != null)
            {
                ViewBag.Name = Session["Name"];
            }
            if (Session["FsCla_Name"] != null)
            {
                ViewBag.FsCla_Name = Session["FsCla_Name"];
            }
            if (Session["count"] != null)
            {
                ViewBag.count = Session["count"];
            }
            if (Session["Subject_count"] != null)
            {
                ViewBag.Subject_count = Session["Subject_count"];
            }
            if (Session["id"] != null)
            {
                ViewBag.id = Session["id"];
                if (id == null)
                {
                    id = int.Parse(Session["id"].ToString());
                }
            }
            if (id == 0 || id == null)
            {
                return Redirect("/Default/Null404");
            }
            if (Session["Name"] != null)
            {
                ViewBag.Name = Session["Name"];
            }
            SvcResult<TSTU_B_Student> Personal = LoginBll.Personal((int)id, int.Parse(Session["classid"].ToString()));
            if (Personal == null)
            {
                return Redirect("/Default/Null404");
            }
            _currentPage = page.HasValue ? page.Value : _currentPage;
            _pageSize = size.HasValue ? size.Value : _pageSize;
            _allProducts = Personal.ObjList;
            ViewBag.size = _pageSize;
            var model = _allProducts.ToPagedList(_currentPage, _pageSize);
            ViewBag.PageCount = Math.Ceiling((double)model.TotalItemCount / (double)model.PageSize);
            return View(model);
        }
        /// <summary>
        /// 总分
        /// </summary>
        /// <returns></returns>
        public ActionResult Total(string name, int? size, int? page = 1)
        {
            ViewBag.stuname = name;
            if (Session["Name"] != null)
            {
                ViewBag.Name = Session["Name"];
            }
            if (Session["FsCla_Name"] != null)
            {
                ViewBag.FsCla_Name = Session["FsCla_Name"];
            }
            if (Session["count"] != null)
            {
                ViewBag.count = Session["count"];
            }
            if (Session["Subject_count"] != null)
            {
                ViewBag.Subject_count = Session["Subject_count"];
            }
            if (Session["id"] != null)
            {
                ViewBag.id = Session["id"];
            }
            if (Session["Name"] == null || Session["FsCla_Name"] == null || Session["count"] == null || Session["Subject_count"] == null)
            {
                return Redirect("/Default/Null404");
            }
            SvcResult<TSTU_B_Score> Result = LoginBll.Result(name);
            ViewBag.total = Result.ObjList;
            if (Result == null)
            {
                return Redirect("/Default/Null404");
            }
            _currentPage = page.HasValue ? page.Value : _currentPage;
            _pageSize = size.HasValue ? size.Value : _pageSize;
            @ViewBag.size = _pageSize;
            var model = Result.ObjList.ToPagedList(_currentPage, _pageSize);
            ViewBag.PageCount = Math.Ceiling((double)model.TotalItemCount / (double)model.PageSize);
            return View(model);
        }


        [HttpPost]
        public ActionResult Total(int? id)
        {
            if (id == 0)
            {
                return Redirect("/Default/Null404");
            }
            SvcResult<TSTU_B_Student> Personal = TeacherBll.Sum_detil((int)id);
            if (Personal.ObjList.Count > 0)
            {
                ViewBag.Personal = Personal.ObjList;
            }
            if (Personal == null)
            {
                return Redirect("/Default/Null404");
            }

            return Json(Personal.ObjList);
        }
        /// <summary>
        /// 各科排名
        /// </summary>
        /// <returns></returns>
        public ActionResult Subject(int? id, int? size, int? page = 1)
        {
            ViewBag.subid = id;
            if (Session["Name"] != null)
            {
                ViewBag.Name = Session["Name"];
            }
            if (Session["FsCla_Name"] != null)
            {
                ViewBag.FsCla_Name = Session["FsCla_Name"];
            }
            if (Session["count"] != null)
            {
                ViewBag.count = Session["count"];
            }
            if (Session["Subject_count"] != null)
            {
                ViewBag.Subject_count = Session["Subject_count"];
            }
            if (Session["id"] != null)
            {
                ViewBag.id = Session["id"];
            }
            if (Session["Name"] == null || Session["FsCla_Name"] == null || Session["count"] == null || Session["Subject_count"] == null)
            {
                return Redirect("/Default/Null404");
            }
            SvcResult<TSTU_B_Subject> Sub = TeacherBll.Sel_Subject();
            ViewBag.sub = Sub.ObjList;
            SvcResult<TSTU_B_Student> Subject_Result = LoginBll.Subject_Result(id);
            if (Subject_Result == null)
            {
                return Redirect("/Default/Null404");
            }
            //分页
            _currentPage = page.HasValue ? page.Value : _currentPage;
            _pageSize = size.HasValue ? size.Value : _pageSize;
            ViewBag.size = _pageSize;
            var model = Subject_Result.ObjList.ToPagedList(_currentPage, _pageSize);
            ViewBag.PageCount = Math.Ceiling((double)model.TotalItemCount / (double)model.PageSize);
            return View(model);
        }
        [HttpPost]
        public ActionResult Subject(int id)
        {
            SvcResult<TSTU_B_Subject> Sub = TeacherBll.Sel_Subject();
            ViewBag.sub = Sub.ObjList;
            SvcResult<TSTU_B_Student> Subject_Result = LoginBll.Subject_Result(id);
            ViewBag.sublist = Subject_Result.ObjList;
            if (Subject_Result == null)
            {
                return Redirect("/Default/Null404");
            }
            ViewBag.Subject = Subject_Result.ObjList;
            //分页
            _allProducts = Subject_Result.ObjList;
            var model = _allProducts.ToPagedList(_currentPage, _pageSize);
            return Json(Subject_Result.ObjList);
        }
        /// <summary>
        /// 登录
        /// </summary>
        /// <returns></returns>
        public ActionResult Login()
        {
            //获取cookie中的数据
            HttpCookie cookie = Request.Cookies.Get("Example");
            //判断cookie是否空值
            if (cookie != null)
            {
                //把保存的用户名和密码赋值给对应的文本框
                //用户名

                var name = cookie.Values["UserName"].ToString();
                ViewBag.UserName = name;
                //密码
                var pwd = cookie.Values["UserPwd"].ToString();
                ViewBag.UserPwd = pwd;
                //账号类型
                if (cookie.Values.AllKeys.Contains("UserType"))
                {
                    var type = cookie.Values["UserType"].ToString();
                    ViewBag.UserType = type;
                }
                
            }
            //ViewBag.UserName = Retrieve("UserName");
            Session.Clear();
            return View();
        }
        [HttpPost]
        public ActionResult Login(string account, string psw, string type, bool Ck)
        {
            ResultErr err = new ResultErr();
            if (Request.IsAjaxRequest())
            {
                if (string.IsNullOrWhiteSpace(account))
                {
                    err.Msg = "错误信息：账号为空";
                    err.Status = 0;
                    return Json(err);
                }
                if (string.IsNullOrWhiteSpace(psw))
                {
                    err.Msg = "错误信息：密码为空";
                    err.Status = 0;
                    return Json(err);
                }
                if (type == "1")
                {
                    SvcResult<TSTU_B_Student> ret = LoginBll.Login_stu(account, psw);
                    if (ret.Error != null)
                    {
                        err.Msg = "错误信息：" + ret.Error;
                        err.Status = 0;
                        return Json(err);
                    }
                    //判断是否记住密码

StudentDBWeb/Views/Default/ForgotPassword.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Forgot Password</title>

    <!-- Custom fonts for this template-->
    <link href="~/Scripts/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/Content/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                                        <p class="mb-4">
                                            We get it, stuff happens. Just enter your email address below
                                            and we'll send you a link to reset your password!
                                        </p>
                                    </div>
                                    <form class="user" >
                                        <div class="form-group">
                                            <select class="form-control" id="exampleFormControlSelect1" name="type" style="border-radius:40px">
                                                <option value="0" selected="selected">----请选择账号类型----</option>
                                                <option value="1">学生</option>
                                                <option value="2">教师</option>
                                                <option value="3">管理员</option>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <input type="email" name="account" class="form-control" style="border-radius:40px"
                                                   id="exampleInputEmail" aria-describedby="emailHelp"
                                                   placeholder="请输入账号...">
                                        </div>
                                        <button type="button" class="btn btn-primary btn-block" style="border-radius:40px">
                                            Reset Password
                                        </button>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="#">Create an Account!</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="#">Already have an account? Login!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/Scripts/vendor/jquery/jquery.min.js"></script>
    <script src="~/Scripts/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Scripts/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Scripts/js/sb-admin-2.min.js"></script>
    <script>
        $(function () {
            $(".user button").click(function () {
                //$(".user").submit()
                //alert($("#exampleFormControlSelect1").val())
                $.ajax({
                    type: 'post',
                    url: '/Default/ForgotPassword',
                    data: {
                        account: $("#exampleInputEmail").val(),
                        type: $("#exampleFormControlSelect1").val()
                    },
                    datatype: 'json',
                    success: function (data) {
                        //data为空，说明成功
                        if (!data) {
                            alert("操作成功【密码重置为：123】")
                            window.location.href = "/Default/Login"
                        } else {
                            alert(data)
                        }
                    },
                    error: function (data) {
                        console.log(data)
                    }
                });
            })
        })
    </script>
</body>

</html>

StudentDBWeb/Views/Default/Personal.cshtml
@model IPagedList<StudentModel.TSTU_B_Student>
    @using StudentModel;
@{
    ViewBag.Title = "Personal";
    Layout = "~/Views/Shared/_StuPage.cshtml";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">个人成绩</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    @using (Ajax.BeginForm("Personal", "Student", new AjaxOptions
                    {
                        InsertionMode = InsertionMode.Replace,
                        HttpMethod = "Post",
                        OnFailure = "searchFailed",
                        UpdateTargetId = "searchresults"
                    }))
                    {

                    }
                    <div class="col-sm-12" id="searchresults">
                        <table class="table table-bordered dataTable" role="grid" aria-describedby="dataTable_info" style="width: 100%;" width="100%" cellspacing="0">
                            <thead>
                                <tr role="row">
                                    <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending">序号</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">姓名</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">学号</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">班级</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">科目</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">讲师</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">成绩</th>
                                </tr>
                            </thead>

                            <tbody>
                                @*<asp:Repeater runat="server" DataSource='<%#ViewData["Students"]%>'>
                                        <template>
                                            <tr role="row">
                                                <td><%#Eval("FsStu_Account")%></td>
                                                <td><%#Eval("FsStu_Account")%></td>
                                                <td><%#Eval("FsStu_Account")%></td>
                                                <td><%#Eval("FsStu_Account")%></td>
                                                <td><%#Eval("FsStu_Account")%></td>
                                                <td><%#Eval("FsStu_Account")%></td>
                                                <td><%#Eval("FsStu_Account")%></td>
                                            </tr>
                                        </template>
                                    </asp:Repeater>*@
                                @foreach (var item in Model.Source)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(modelItem => item.rownumber) </td>
                                        <td>@Html.DisplayFor(modelItem => item.FsStu_Name) </td>
                                        <td>@Html.DisplayFor(modelItem => item.FsStu_Account) </td>
                                        <td>@Html.DisplayFor(modelItem => item.FsCla_Name)  </td>
                                        <td>@Html.DisplayFor(modelItem => item.FsSub_Name)  </td>
                                        <td>@Html.DisplayFor(modelItem => item.FsTea_Name)  </td>
                                        <td>@Html.DisplayFor(modelItem => item.FnSco_Result)  </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12 col-md-3">
                        <div id="dataTable_info" role="status" aria-live="polite">
                            当前第 @Model.CurrentPage/@ViewBag.PageCount 页 每页显示 @Model.PageSize 条数据 共 @Model.TotalItemCount 条数据
                        </div>
                    </div>

                    <div class="col-md-3 col-sm-12">
                        @using (Html.BeginForm("Personal", "Default", FormMethod.Get, new { id = "PagingForm" }))
                        {
                            <div class="dataTables_length" id="dataTable_length">
                                <label>
                                    Show
                                    <select name="size" aria-controls="dataTable" class="custom-select custom-select-sm form-control form-control-sm">
                                        <option value="@ViewBag.size">@ViewBag.size</option>
                                        <option value="5">5</option>
                                        <option value="10">10</option>
                                        <option value="20">20</option>
                                        <option value="30">30</option>
                                        <option value="50">50</option>
                                        <option value="70">70</option>
                                        <option value="100">100</option>
                                    </select>
                                    entries
                                </label>
                            </div>
                        }
                    </div>

                    <div class="col-sm-12 col-md-6">
                        <div class="dataTables_paginate paging_simple_numbers" id="dataTable_paginate">
                            @Html.Pager(Model.PageSize, Model.CurrentPage, Model.TotalItemCount).Options(o => o.HtmlAttributes(new { @class = "pagination" }).RouteValues(new { size = ViewBag.size }))
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

StudentDBWeb/Views/Default/Total.cshtml
@model IPagedList<StudentModel.TSTU_B_Score>
@using StudentModel;
@using System.Data;
@{
    ViewBag.Title = "Total";
    Layout = "~/Views/Shared/_StuPage.cshtml";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">总分排名</h6>
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-2 offset-sm-6 offset-md-8 offset-lg-9 offset-xl-10">
                        @using (Html.BeginForm("Total", "Default", FormMethod.Get))
                        {
                            <div class="input-group">
                                <input type="hidden" value="@ViewBag.size" name="size" />
                                <input type="text" name="name" class="form-control bg-light border-0 small" placeholder="请输入姓名查询..." aria-label="Search" id="id" aria-describedby="basic-addon2" value="@ViewBag.stuname">
                                <div class="input-group-append ">
                                    <button type="submit" class="btn btn-primary">
                                        <i id="ajax-loader" class="fas fa-search fa-sm"></i>
                                    </button>
                                </div>
                            </div>
                        }
                    </div>

                    <div class="col-sm-12">
                        <table class="table table-bordered dataTable" role="grid" aria-describedby="dataTable_info" style="width: 100%;" width="100%" cellspacing="0">
                            <thead>
                                <tr role="row">
                                    <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending">序号</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">姓名</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">学号</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">班级</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">总分</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">平均分</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">操作</th>
                                </tr>
                            </thead>

                            <tbody class="Total_tbody">
                                @*@Html.Action("_PartialPage", Model)*@



                                @if (Model != null)
                                {

                                    foreach (var item in Model.Source)
                                    {
                                        <tr>
                                            <td>@item.rownumber </td>
                                            <td>@item.FsStu_Name </td>
                                            <td>@item.FsStu_Account </td>
                                            <td>@item.FsCla_Name </td>
                                            <td>@item.sum </td>
                                            <td>@item.avg </td>
                                            <td>
                                                <button class="btn btn-success btn-icon-split btn_model" id="btn_model" data-toggle="modal" data-target="#exampleModal" onclick="Sel(@item.FnStu_ID)" data-whatever="@item.FnStu_ID">
                                                    <span class="text">查看</span>
                                                </button>

                                            </td>
                                        </tr>
                                    }
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row fenye">
                    @if (Model != null)
                    {
                        <div class="col-sm-12 col-md-3">
                            <div id="dataTable_info" role="status" aria-live="polite">
                                当前第 @Model.CurrentPage/@ViewBag.PageCount 页 每页显示 @Model.PageSize 条数据 共 @Model.TotalItemCount 条数据
                            </div>
                        </div>

                        <div class="col-md-3 col-sm-12">
                            @using (Html.BeginForm("Total", "Default", FormMethod.Get, new { id = "PagingForm" }))
                            {
                                <div class="dataTables_length" id="dataTable_length">
                                    <label>
                                        Show
                                        <input type="hidden" value="@ViewBag.stuname" name="name" />
                                        <select name="size" aria-controls="dataTable" class="custom-select custom-select-sm form-control form-control-sm">
                                            <option value="@ViewBag.size">@ViewBag.size</option>
                                            <option value="5">5</option>
                                            <option value="10">10</option>
                                            <option value="20">20</option>
                                            <option value="30">30</option>
                                            <option value="50">50</option>
                                            <option value="70">70</option>
                                            <option value="100">100</option>
                                        </select>
                                        entries
                                    </label>
                                </div>
                            }
                        </div>

                        <div class="col-sm-12 col-md-6">
                            <div class="dataTables_paginate paging_simple_numbers" id="dataTable_paginate">
                                @Html.Pager(Model.PageSize, Model.CurrentPage, Model.TotalItemCount).Options(o => o.HtmlAttributes(new { @class = "pagination" }).RouteValues(new { name = ViewBag.stuname, size = @ViewBag.size }))
                            </div>

                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable ">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">分数详情</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input type="hidden" class="form-control" id="recipient-name" name="id">
                <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                    <div class="row">
                        <div class="col-sm-12">
                            <h3></h3>
                            <table class="table table-bordered dataTable" id="" role="grid" aria-describedby="dataTable_info" style="width: 100%;" width="100%" cellspacing="0">
                                <thead>
                                    <tr role="row">
                                        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">科目</th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">成绩</th>
                                    </tr>
                                </thead>

                                <tbody id="stumodeltbody">
                                    @*@if (ViewBag.Personal != null)
                                        {
                                            foreach (var item in ViewBag.Personal as List<TSTU_B_Student>)
                                            {
                                                <tr>
                                                    <td>@item.FsSub_Name</td>
                                                    <td>@item.FnSco_Result</td>
                                                </tr>
                                            }
                                        }*@

                                    @*@foreach (var item in Model)
                                        {

                                            <tr>
                                                <td>@Html.DisplayFor(modelItem => item.FsSub_Name)</td>
                                                <td>@Html.DisplayFor(modelItem => item.FnSco_Result)</td>
                                            </tr>
                                        }*@

                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>